gem 'rails', '4.0.11'
gem 'pg'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'geocoder'
gem 'gmaps4rails'
gem 'haml'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'bootstrap_form'

group :doc do
  gem 'sdoc', require: false
end

group :test do
  gem 'pry-byebug'
end
